"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-)^wax!_t^hkw!m2_=u0&2(70w8sm+5fq!gioibm5359mhy1s^a',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Por defecto False (no True): si DJANGO_DEBUG no llega a estar definida
# en el entorno (por ejemplo, un despliegue nuevo sin .env y sin la
# variable configurada todavia), el fallo seguro es NO mostrar tracebacks
# con detalles internos, no al revés. En local, .env.example ya define
# DJANGO_DEBUG=True explicitamente, asi que esto no cambia el flujo de
# desarrollo de siempre.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()
]
# Cualquier subdominio de Render (el hostname exacto lo agrega
# RENDER_EXTERNAL_HOSTNAME mas abajo, pero este wildcard cubre el caso de
# que esa variable no este disponible en algun punto, p.ej. durante el
# build) - Canigo nunca se sirve desde un dominio propio todavia.
ALLOWED_HOSTS.append('.onrender.com')

# Mismo criterio que ALLOWED_HOSTS: el wildcard de Render siempre
# presente, ademas (no en vez) de cualquier origen manual que se agregue
# por variable de entorno.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]
CSRF_TRUSTED_ORIGINS.append('https://*.onrender.com')

# Render inyecta esta variable automaticamente con el hostname publico del
# servicio (p.ej. "canigo-xxxx.onrender.com") - la agregamos sola, sin que
# haya que configurar DJANGO_ALLOWED_HOSTS a mano en cada deploy.
_RENDER_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _RENDER_HOSTNAME:
    ALLOWED_HOSTS.append(_RENDER_HOSTNAME)
    CSRF_TRUSTED_ORIGINS.append(f'https://{_RENDER_HOSTNAME}')

# Render sirve todo detras de un proxy TLS: sin esto, Django no reconoce
# los requests como HTTPS (rompe CSRF y las cookies "secure").
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Render ya redirige http->https en su propio proxy, pero esto es una
    # segunda capa dentro de la propia app (warning W008 de `manage.py
    # check --deploy`, de las que SI vale la pena corregir: no rompe nada,
    # es la recomendacion basica de seguridad de Django). HSTS (W004) NO
    # se activa aca a proposito - el propio warning de Django avisa que
    # mal configurado puede causar problemas dificiles de revertir
    # (queda "pegado" en el navegador por el tiempo que se le indique),
    # y no fue pedido explicitamente - se reporta en vez de activarse.
    SECURE_SSL_REDIRECT = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'core',
    'usuarios',
    'mascotas',
    'paseos',
    'notificaciones',
    'coordenadas',
    'incidentes',
    'calificaciones',
    'administracion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.notificaciones',
                'core.context_processors.es_admin',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# El disco de un Render web service es efimero (se reinicia en cada deploy),
# asi que esta sqlite tampoco sobrevive entre deploys. Como solo la usamos
# para la maquinaria interna de Django (admin/auth/contenttypes, que no
# usamos activamente), no perdemos datos de negocio - esos viven en Mongo.
# Pero las sesiones (login web del dueño) SI nos importan, y por defecto
# tambien viven en esa sqlite: las guardamos en una cookie firmada en vez de
# en la base de datos para que un dueño no quede deslogueado cada vez que
# se hace un nuevo deploy.
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

# MongoDB Atlas (base de datos de negocio de Canigo)
# El ORM de Django + sqlite de arriba solo sostiene el propio maquinaria de
# Django (sessions, admin, etc.). Las colecciones del dominio (usuarios,
# mascotas, paseos, coordenadas_detalle, incidentes, calificaciones,
# notificaciones) viven en MongoDB Atlas y se acceden vía pymongo (ver
# core/mongo.py), sin capa ORM intermedia.
MONGO_URI = os.environ.get('MONGO_URI', '')
MONGO_DB_NAME = os.environ.get('MONGO_DB_NAME', 'canigo')

# Cloudinary (almacenamiento de imagenes: foto_perfil, foto de mascota,
# fotos de paseo, evidencia de incidentes). Se usa en vez del filesystem de
# Render porque este ultimo es efimero (se borra en cada redeploy).
# Formato: cloudinary://<api_key>:<api_secret>@<cloud_name>
CLOUDINARY_URL = os.environ.get('CLOUDINARY_URL', '')

# Panel de administracion de Canigo (RF14 - verificacion de paseadores):
# NO es un rol nuevo en `usuarios` (ver CLAUDE.md, solo "dueño"/"paseador").
# Una cuenta ya existente (de cualquier rol) es administradora si su correo
# esta en esta lista - ver usuarios/decorators.py::requiere_admin().
CANIGO_ADMIN_EMAILS = [
    correo.strip().lower()
    for correo in os.environ.get('CANIGO_ADMIN_EMAILS', '').split(',')
    if correo.strip()
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# Bootstrap/Leaflet se cargan por CDN (ver core/templates/base.html), asi
# que lo unico que Django sirve como estatico es el CSS del admin. WhiteNoise
# lo sirve directamente desde el proceso de Django (comprimido, con cache
# busting), sin necesitar Nginx ni un bucket aparte.

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
